### ISSUE TITLE
unable to get origin file in Android ? 

### ISSUE THREAD

**Issue by senbaisang** [lowb1rd/TiMediaPicker#11]
hi there, 

   this is a very useful & powerful module, it works very well under ios, however, we are not able to get origin file in Android when selecting the thumbnails.

The scenario is: 
1. enter the image gallery. 
2. choose the images we want to upload. 
3. click the 'OK'
   
   However, the images that sent to background server are the "thumbnails", but not the "origin images".  
   
   my question is , are we able to get the origin files in this scenario? 

thanks.
Siwei

**Comment by sg552** [comment]
oh yeah, We don't have this problem. 

use :  url attribute will work.  e.g.
