### ISSUE TITLE
Selection only shows 16 images

### ISSUE THREAD

**Issue by ppennings** [lowb1rd/TiMediaPicker#15]
Lately (I don't know exactly since with version of IOS) the mediapicker only shows 16 images to select from. These are shown in 2 columns on the left halve of the screen.

**Comment by natefollmer** [comment]
What version of iOS and device? Still working as planned on my end, but I'm testing on the emulator (iPhone 5S, v9.3)

**Comment by ppennings** [comment]
I'm testing on 9.3 and 5s and have the same problem. Also on all later versions of iPhone and iOS .
Strange thing is that when I scroll down, sometimes 2 images will be added, but not on every swipe.

**Comment by natefollmer** [comment]
Sorry, I didn't get notification that you responded. 

What Titanium SDK are you using? I'm building with 5.3.1.GA. I can't replicate your issue. My iOS code is identical to the example provided. I only changed my Android code as it wasn't respecting the images orientation flags, so I have to make my own thumbnails now.

**Comment by ppennings** [comment]
NP, I just returned from a 3 week Holliday :)

I just tried out a simpler test app and that worked (should have done that earlier off course). Turns out I used an older version of mediapicker.js

Problem solved, thx for your input !
