### ISSUE TITLE
mediawindow showing only 2 columns

### ISSUE THREAD

**Issue by skoften** [lowb1rd/TiMediaPicker#7]
SDK 3.5.1.GA

![media](https://cloud.githubusercontent.com/assets/1286410/6769240/120558dc-d093-11e4-8131-7e54be5dbb76.jpg)

Happens on iPhone 4, 5 and 6 emulator and real device.

**Comment by lowb1rd** [comment]
This is because Ti.Platform.displayCaps.logicalDensityFactor used to return always 1 on iOS and from TiSDK 3.5.0 it return 2 for retina devices. A fix is on its way..
